# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00c9c81fee1b59d276ce5458668204d80796965e3a45512fcea3f9e85b579cb5397587d90e2d648678d079c8444b35051a6e889393db35e673a1c1760b266dd0

test:
  secret_key_base: 61d7fb7ede3e3394b5acc3e60f0b7c98714decb549819b55c3d92f9800ee2580c83836268777c9f3cb52d5a23f6f94e6d1dc8f9e7a04e87318fa4dca0dfec6fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
